services:
    ctm:
        image: docker.io/florianscholzsrssoftware/christmas-tree-manager:latest
        container_name: christmas-tree-manager
        restart: always
        ports:
            - 8080:80
            - 8081:443
        volumes:
            - .:/app/mnt/
        environment:
            - ASPNETCORE_HTTP_PORTS=80
            - ASPNETCORE_HTTPS_PORTS=443
            - ASPNETCORE_Kestrel__Certificates__Default__Password=ctm
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/mnt/aspnetapp.pfx

    sqlitebrowser:
        image: linuxserver/sqlitebrowser
        ports:
            - 3000:3000
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=UTC
            - ENABLE_UWSGI=true
        volumes:
            - .:/data/db
        container_name: sqlitebrowser

# database file and folder need write permissions